name: "llms-txt-action"
description: "Convert documentation websites into LLM-ready by adding /llms.txt. reference: https://llmstxt.org/."
branding:
  icon: "book"
  color: "blue"

inputs:
  docs_dir:
    description: "Documentation output directory"
    required: false
    default: "site/"
  generate_llms_txt:
    description: "Whether to generate LLMS.txt file"
    required: false
    default: "true"
  llms_txt_name:
    description: "LLMS.txt file name"
    required: false
    default: "llms.txt"
  generate_md_files:
    description: "generate md files for each html file"
    required: false
    default: "true"
  # formats:
  #   description: "Output formats (comma-separated: html,markdown,metadata)"
  #   required: false
  #   default: "html,markdown,metadata"
  poetry-version:
    description: "Poetry version to use (or 'latest')"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install pipx
      shell: bash
      run: |
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath

    - name: Install Poetry
      shell: bash
      run: |
        if [[ "${{ inputs.poetry-version }}" == "latest" ]]; then
          pipx install poetry
        else
          pipx install poetry==${{ inputs.poetry-version }}
        fi

    - name: Get Poetry cache dir
      id: poetry-cache
      shell: bash
      run: |
        echo "dir=$(poetry config cache-dir)" >> $GITHUB_OUTPUT

    - name: Setup Poetry cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.poetry-cache.outputs.dir }}
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        poetry install --no-interaction --no-root

    - name: Run llms-txt-action
      shell: bash
      run: |
        cd ${{ github.action_path }}
        poetry run python src/llms-txt-action/main.py

    - name: Commit changes
      shell: bash
      run: |
        cd ${{ inputs.docs_dir }}
        git add .
        git commit -m "Generated LLMS.txt file"
        git push
