name: E2E Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction
          pip install mkdocs

      - name: Build test docs
        run: |
          cd tests/test_mkdocs
          mkdocs build

      - name: Run llms-txt
        run: |
          cd tests/test_mkdocs
          poetry run llms-txt --docs-dir site/

      - name: Check generated files
        run: |
          cd tests/test_mkdocs
          if [ ! -f "site/index.md" ]; then
            echo "index.md not found"
            exit 1
          fi
          if [ ! -f "site/llms.txt" ]; then
            echo "llms.txt not found"
            exit 1
          fi
          if [ ! -f "site/llms_full.txt" ]; then
            echo "llms_full.txt not found"
            exit 1
          fi
