name: Generate LLM Texts
on:
  workflow_call:
    inputs:
      base_url:
        required: true
        type: string
        description: "Base URL to crawl"
      output_dir:
        required: false
        type: string
        default: "docs/crawled"
        description: "Directory to save crawled data"
    secrets:
      api_key:
        required: true
        description: "Firecrawl API key"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate texts
        env:
          BASE_URL: ${{ inputs.base_url }}
          API_KEY: ${{ secrets.api_key }}
          OUTPUT_DIR: ${{ inputs.output_dir }}
        run: python -m docs_actions.generate_texts
